@startuml

[*] --> MENU
MENU: 1. Aku
MENU: 2. Dia
MENU --> PILIHAN
PILIHAN : Masukkan Pilihan Anda
PILIHAN --> MENU: Pilihan Anda Salah
PILIHAN --> AKU: OK
PILIHAN --> DIA: OK
AKU --> [*]: SELESAI
DIA --> [*]: SELESAI

@enduml